##### A small, ad-hoc script to write json file from loaded Figaro template for PLATES
# Almost certainly it will need customization, and it is therefore given as-is
# Also, expect to tweak manually the template in particular:
# plt.col are converted to real colour names
# options have to be manually implemented
# Text entered as expression should be manually typed
# Template elts for A, B and C, the ternary apices (generated by the parser) should
# be removed from the json
# .. and often, log specifications as well

#### Main function ####
readFigaroTemplate<-function(diag){

  xlims <- diag$demo$call$xlim
  ylims <- diag$demo$call$ylim

  xAxis <- as.character(diag$demo$call$xlab)
  yAxis <- as.character(diag$demo$call$ylab)

  ## X and Y scale (log or natural)

  islog <- as.character(diag$demo$call$log)

  template <- diag$demo$template

  for(i in 1:length(template)){
    # Add name to the first element
    nm <- names(template[[i]])
    names(template[[i]]) <- c("plotFun",nm[-1])
  }


  return(list(
    name = diag$demo$call$diagram,
    fullName = diag$demo$template$GCDkit$plot.name,
    details = "",
    reference = "",
    url = "",
    templateAuthor= "V. Erban <erban@sopky.cz>, V. Janoušek <vojtech.janousek@geology.cz>",
    templateConversion = "J.-F. Moyen <jfmoyen@gmail.com>",
    templateHistory = "Converted from original GCDkit function",
    RDialect = "base",
    optionSwitches = list(showText= "Default option to show diagram text"),
    optionDefaults = list(showText= T),
    diagramType=sheet$demo$template$GCDkit$plot.type,
    dataTransform = NULL,
    axesDefinition = list(X=xAxis,Y=yAxis),
    limits=list(X=xlims,Y=ylims),
    log=islog,
    template = template
  ))
}

##########
ee<-readFigaroTemplate(plate[[1]])
# ee$template$B$text<-NULL ##When text appears as expression
ee.json <- prettify(toJSON(ee,null="null",auto_unbox = T))
write(ee.json,"./inst/json_templates/plate_components/Frost_fig1.json")
